### PR TITLE
Divide logos carousel by two rows

### PR DESCRIPTION
**Pull request by mfrecchiami**
In this PR we're going to display the logos carousel on the homepage in two rows. A hover color has been added, also.

### Before
Screenshot 2021-05-11 at 09 38 20

### After
Screenshot 2021-05-11 at 09 38 08

### CODE REVIEW

**Comment by davidedistefano** [comment]
@mfrecchiami Can we reduce the animation a little bit? 

I'd also reduce the spacing between logos and rows.

**Comment by mfrecchiami** [comment]
> @mfrecchiami it looks great!
> 
> I noticed that if you click one of the logos the endless scrolling stops and re-starts only if I click on another logo.

Thanks for notice that @mtylty! I've fixed it right now 🚀

**Comment by mfrecchiami** [comment]
> @mfrecchiami Can we reduce the animation a little bit?
> 
> I'd also reduce the spacing between logos and rows.

@davidedistefano do you mean reduce the animation speed or the container width?
About the spacing, do you mean the margin around the single logo (left, right, top, bottom)?

**Comment by mfrecchiami** [comment]
@davidedistefano adjustments pushed ✔️

**Review by davidedistefano — APPROVED** [review]
Looks good to me 👍

**Review by kennyadsl — APPROVED** [review]

**Pull request merged**
