### PR TITLE
Social share cards

### PR DESCRIPTION
**Pull request by kennyadsl**
Check the result here:

https://cards-dev.twitter.com/validator

Screenshot 2020-05-04 at 15 57 58
Screenshot 2020-05-04 at 15 57 03
Screenshot 2020-05-04 at 15 56 48
Screenshot 2020-05-04 at 15 57 36

### CODE REVIEW

**Comment by mfrecchiami** [comment]
@kennyadsl I'm not so sure that the image that I've done, could be ok 🤔 
I think that the copy inside the image is not necessary (and results overflowing) since there're meta tags when somebody shares a page.
I'm going to do a better image for it, give me a moment pls

**Comment by kennyadsl** [comment]
@mfrecchiami sure, take your time!

**Comment by mfrecchiami** [comment]
@kennyadsl here the new general image for the links sharing: 

solidus-sharing-link

Many thanks 🙂

**Comment by kennyadsl** [comment]
@mfrecchiami here's the new preview:

Screenshot 2020-05-04 at 17 34 44

**Pull request merged**
