### PR TITLE
Add Affirm V2 blog post

### PR DESCRIPTION
**Pull request by peterberkenbosch**
currently in draft

- [x] move v2 extension from personal repo to solidusio-contrib
- [x] figure out why middleman ignores or fails to build this post
- [x] review on style / content / typos etc

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
This one can use a different / better header image I think. @mfrecchiami is that something you can  and want to do? //cc @aldesantis @kennyadsl

**Comment by kennyadsl** [comment]
The images are very heavy, can we give them a pass into https://compressor.io/, please?

**Comment by peterberkenbosch** [comment]
@kennyadsl Oops, yeah a bit on the heavy side :) Compressed now

**Comment by mfrecchiami** [comment]
Hi @peterberkenbosch !
I've done the cover image for your blog post:
increase_revenue_with affirm

It would be nice to use the syntax highlighter for the code instead of terminal screenshots.

**Comment by peterberkenbosch** [comment]
Awesome! Thanks! 

I agree on the code samples. I will update those in a sec.

Peter.

**Comment by kennyadsl** [comment]
Hey Peter! Can we change the post date to next week? We are already publishing two posts this week (community day and monthly update) and I think it's better to spread them.

**Comment by peterberkenbosch** [comment]
@kennyadsl For sure! Will push update with that change in a sec.

**Comment by peterberkenbosch** [comment]
@kennyadsl can we publish this?

**Comment by kennyadsl** [comment]
Sure!

**Pull request merged**
