### PR TITLE
Update extensions list

### PR DESCRIPTION
**Pull request by aldesantis**
Updates the list of extensions with the latest changes and additions.

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]
Thanks!

**Comment by kennyadsl** [comment]
Re-running Netlify deploy

**Comment by kennyadsl** [comment]
There's something preventing the build to succeed, does `middleman build` work locally for you?

**Comment by aldesantis** [comment]
@kennyadsl fixed, it was just a couple of typos!

**Pull request merged**
