### PR TITLE
Group and animate the community brands on the homepage

### PR DESCRIPTION
**Pull request by mfrecchiami**
This PR introduces a solution that lets us show more brands without displaying them on more than two rows (one row on medium/large screen).

Schermata 2020-09-01 alle 11 22 24

The brands slide vertically with a CSS animation.

### CODE REVIEW

**Review by davidedistefano — COMMENTED** [review]
I think we can add one more logo to the row, what do you think?

**Comment by mfrecchiami** [comment]
Yes, now there're 12 logos and I grouped them x3; if I group x2 there'll be 6 logos on one row. 
For now the animation doesn't work asynchronously.

**Comment by mfrecchiami** [comment]
@davidedistefano I've tried to duplicate the `@keyframes` animation to manage 4 items (logos) instead of 3.
I noticed that we should avoid using this animation to rotate/slide less than 3 items per cycle.

I've also added some new brands, so now the number of items displayed is 5 per 1 row. The total of brands is 16.

**Comment by mfrecchiami** [comment]
@kennyadsl @aldesantis what do you think about this solution? 
In this way we can show more brands/change brands to show.

**Comment by kennyadsl** [comment]
I think it works, maybe the animation makes the logos appear too close to the title?

**Comment by davidedistefano** [comment]
> I think it works, maybe the animation makes the logos appear too close to the title?

**Comment by davidedistefano** [comment]
We can increase the title margin-bottom a little bit, like `mb-5`.

**Comment by mfrecchiami** [comment]
@aldesantis I'd like to use the new `brands.yml` also for the brands' carousel on the homepage.
In this case the logos were grouped, sometimes 3 per group, sometimes 4. And have to apply additional class for the group of 4 items. 

I don't know if it's worth (and if it's possible, either) adding these additional variables to the `brands.yml`.

Maybe we can go online with this version and then think about this refinement.

**Comment by mfrecchiami** [comment]
@davidedistefano the previous animation was more catchy maybe but with this solution, we can use `brands.yml` like all the other pages of the site. 
It uses the slick-carousel JS that is already used by the testimonials' carousel.

**Comment by davidedistefano** [comment]
@mfrecchiami I also prefer the previous animation, but I guess we don't have much choice. We might also try something like [this](https://www.homerun.co/) (which is a continuous carousel) but inside the website container, maybe adding a sort of fade overlay on the left and right sides.

**Comment by mfrecchiami** [comment]
@davidedistefano done ✅ 
I think that now it works better!

**Comment by davidedistefano** [comment]
@mfrecchiami Agreed, much better! I'd only reduce the size of the logos on mobile a little bit and we're good to go imo.

**Comment by mfrecchiami** [comment]
@davidedistefano I've refined the size of the brands so now they are more proportionate between themselves.
I think that now logos display well also on the mobile view!

**Comment by mfrecchiami** [comment]
@aldesantis the order of the brands now is based on the most famous to the least; do you think this version could be fine?

**Comment by davidedistefano** [comment]
@mfrecchiami Looks good to me 👍

**Comment by davidedistefano** [comment]
@mfrecchiami Sorry, one thing I forgot to say. It'd be nice if possible to stop the animation while hovering an item.

**Comment by mfrecchiami** [comment]
@davidedistefano actually the option `pauseOnHover` is set as `true` by default. I noticed there's a [bug](https://github.com/kenwheeler/slick/issues/500), it seems related with the option `autoplay: true`. 
I've tried the workaround suggested [here](https://github.com/kenwheeler/slick/issues/500#issuecomment-522829807): it works but it gives a bunch of errors (about jquery) 😞 

I've tried also to change some options (i.e. the value of `slideToScroll` and the `0` of the `autoplaySpeed`) instead to follow that workaround: in this way, I don't receive errors but the pause on hover works so and so.

Maybe is it the case to think about using another vendor for the carousels?

**Comment by davidedistefano** [comment]
@mfrecchiami Oh, too bad. Yes, we can change the plugin if it doesn't take much time.

**Comment by aldesantis** [comment]
@mfrecchiami just to add more stuff to your plate (sorry!), I noticed that it feels a bit weird that the logos scroll and disappear before the edge of the screen. I tried using `.container-fluid` and showing more logos, but I realize that the right number of logos to display in that case would depend on the size of the screen. Not sure if there's a good solution.

Anyway, I'm 100% for going with the current implementation. It's still better than what we have right now.

**Comment by mfrecchiami** [comment]
@aldesantis I'm pretty sure that we can manage the number of logos to show, with the `breakpoint` option of the JS carousel.
I like the wide container, but I'm not sure of the final result. Perhaps will it crowd of logos on wide screens?

I think is better to try this solution in another PR, so we can see the difference between this one and the second one with `container-fluid`.

**Comment by mfrecchiami** [comment]
@davidedistefano now the `pauseOnHover` works!
I've changed some parameters and... 🎉 

> @davidedistefano actually the option `pauseOnHover` is set as `true` by default. I noticed there's a [bug](https://github.com/kenwheeler/slick/issues/500), it seems related with the option `autoplay: true`.
> I've tried the workaround suggested [here](https://github.com/kenwheeler/slick/issues/500#issuecomment-522829807): it works but it gives a bunch of errors (about jquery) 😞
> 
> I've tried also to change some options (i.e. the value of `slideToScroll` and the `0` of the `autoplaySpeed`) instead to follow that workaround: in this way, I don't receive errors but the pause on hover works so and so.
> 
> Maybe is it the case to think about using another vendor for the carousels?
> https://flickity.metafizzy.co/ for example

**Comment by davidedistefano** [comment]
@mfrecchiami Now it's perfect 🎉

**Comment by aldesantis** [comment]
@mfrecchiami is this good to merge? 🙂

**Review by davidedistefano — APPROVED** [review]
We're good to go 🚀

**Pull request merged**
